### ISSUE TITLE
Error when starting with CTRL+F12

### ISSUE THREAD

**Issue by IbnSaeed** [johndgiese/vipy#10]
I am getting the following error on a fresh install of vipy in gvim 7.4 running under Arch Linux.

When i press CTRL + F12 on a .py file, i get the following in the vim buffer area.

```
Starting VIPY! This may take a few seconds...
Error detected while processing /home/user/.vim/bundle/vipy/main.vim:
line   20:
E128: Function name must start with a capital or "s:": g:vipySyntax()
line   24:
E193: :endfunction not inside a function
```

**Comment by johndgiese** [comment]
I apologize, however I don't have time to support this project right now; if you can figure it out, please feel free to submit a pull request!

**Comment by IbnSaeed** [comment]
Wouldnt it be better if you would post a note on the main page saying that this project is Not being developed anymore.
