### ISSUE TITLE
Locks up vim (100% CPU)

### ISSUE THREAD

**Issue by blueyed** [johndgiese/vipy#11]
I have tried using vipy, inside of a virtualenv, where I have `pyzmq==14.1.1` installed.

After pressing `<c-f12>` the terminal window looks messed up (as follows) and the vim process takes 100% CPU, and needs to be `kill -9`ed after closing the terminal window.

```
Starting VIPY! This may take a few seconds...
You must have pyzmq >= 2.1.4 installed to use ViPy.
Press ENTER or type command to continueNOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

      To exit, you will have to explicitly quit this process, by either sending
                                                                               "quit" from a client, or using Ctrl-\ in UNIX-like environments.

                                      To read more about this, see https://github.com/ipython/ipython/issues/2049


        To connect another client to this kernel, use:
                                                          --existing kernel-8897.json
```

I have just tried it using a clean/temporary virtualenv, with just ipython and pyzmq installed - with the same result.

Python 2.7.6, Ubuntu 14.04.

**Comment by toomanycats** [comment]
I'm having the same issue with Ubuntu 14.04, python2.7.6 vim 7.4 +python, pymqz 14.5.0  from anaconda . 

I start vim, then press <control> <f12> and I get high CPU usage and non-responsive terminal.

FYI, Vim and advanced ipython features are new to me so I'm a bit lost. Having some difficulty understanding how this works in general. 

TIA, 
this looks like a great utility.

**Comment by johndgiese** [comment]
@toomanycats thanks for reaching out; unfortunately I am too busy these days to continue supporting this project (that I no longer use).

In the end, I decided that connecting vim with ipython was actually a bad idea that breaks the unix philosophy of doing one thing well.

I know think that a better way to get 90% of what I wanted out of vipy, is to use tmux, open ipython in the right split, open vim in the left split, and use a simple vim macro to move visually selected text between the two.  This is much much simpler, lets you use ipython in all its glory, and doesn't make vim into something its not designed to be.

You can see an example of a vim macro that does this here:

https://github.com/johndgiese/dotvim/blob/master/vimrc#L502
