### ISSUE TITLE
Vim exiting on startup

### ISSUE THREAD

**Issue by pag** [johndgiese/vipy#2]
In main.vim you have:

```
if major == 0 and minor > 13:
    vprint([
        "It appears you have IPython {}.{} installed.".format(major, minor),
        "You must have IPython 0.13 or newer installed to use ViPy.",
    ])
    sys.exit()
```

I assume that comparison should be `if ... minor < 13`, it's failing for me on IPython 0.14. Also, why do you use `sys.exit()` all over that file? It seems to be shutting down my Vim (MacVim, Mac OS X). Can't you just raise an exception other than SystemExit?

**Comment by johndgiese** [comment]
Thanks for letting me know about this; I have 0.13 so its worked for me thus far.  I fixed the code directly on Github, so I believe it should work as expected now.

By the way, I am working on a second version for ViPy at the moment, which will have much cleaner code (I was just learning python and vim when I put this together the first time)
