### ISSUE TITLE
Change documentation to reflect that running :py vipy_startup() requires sourcing of main.vim

### ISSUE THREAD

**Issue by jorgsk** [johndgiese/vipy#4]
Hi and let me say I'm really excited about working with python and Vim in this way.

Some startup problems however. I've installed ipython 13.2 and pyzmq,and vim is compiled with +python. I've installed vipy with Vundle (14th of April) and I'm on linux.

However, when I try ":py vipy_startup()" the function is not recognized.

When I then try ":source vipy/plugin/vipy.vim" I get the message that SourceMain is already defined, so this file is correctly sourced. In order to run vipy I have to manually run ":source vipy/main.vim". Then I can lauch vipy_startup() to get an ipython buffer and everything you have documented seems to work (<leader>5, F9 etc).

Thanks again for making this project!

**Comment by jorgsk** [comment]
OK, I've found the problem. There are two issues here.

1) the <C-F12> mapping didn't work for me (no idea why) so I remapped it to <F8> which seems fine.
2) one cannot run ":py vipy_startup()" without first having sourced main.vim.

Point 1) is a special case on my computer, but 2) should be reflected in the documentation (since now it says run C-F12 or :py vipy_startup()) -- it should say "press <C-F12> or :call SourceMain() followed by :py vipy_startup()"

**Comment by johndgiese** [comment]
Sorry it has been a while; I am working on a rewrite of vipy that will eliminate these issues, so for now I simply removed the comment in the README, but hopefully soon I will add the ability to customize all of the vipy mappings, and thus this won't really be an issue anymore.

David
